### ISSUE TITLE
Problem with ReCaptcha for product reviews

### ISSUE THREAD

**Issue by bohdanchumak** [swissup/module-easytabs#32] opened 2023-07-07 10:26 UTC
The client has enabled Google ReCaptcha v3 (the built-in one, not our module) for the reviews form. However, when the Easy Tabs module is enabled, it throws an "Invalid ReCaptcha" message if you try to add a review. With Easy Tabs disabled, everything seems to be working fine.

LWA-10859

**Comment by tangar76** [comment] 2023-07-07 12:55
I can't reproduce this issue at my local instance.
Magento Google Recaptcha V3 works fine with review form in easytabs. Is there a recaptcha badge somewhere in post review form?

**Comment by tangar76** [comment] 2023-07-11 14:41
Issue occurs when reviews tab is loaded via Ajax. Not ajax tab has no problems.

Before close this issue check how to solve this one https://github.com/swissup/module-easytabs/issues/20

**Comment by tangar76** [comment] 2023-07-12 08:31
Issue #20 fixed with triggering `beforeOpen` event at https://github.com/swissup/module-easytabs/blob/master/view/frontend/web/js/tabs.js#L49

So the issue with missing recaptcha at review form occurs only when tab with this form is loaded via ajax.
Disable load tab with ajax for reviews tab. Currently there is no better solution.

**Closed by tangar76** 2023-07-12 08:31 UTC
